### ISSUE TITLE
这个创建共享内存的进程销毁后,数据是存储在哪里了呢?

### ISSUE THREAD

**Issue by maxbad** [williamxin/smd#1]
这个创建共享内存的进程销毁后,数据是存储在哪里了呢?

**Comment by yongxin-ms** [comment]
数据存在共享内存啊，linux下的共享内存是操作系统管理的，独立于进程的

**Comment by maxbad** [comment]
哦.我以为windows也可以呢 !😜

**Comment by yongxin-ms** [comment]
Windows需要你至少开一个进程持有那片共享内存，然后共享内存的数据就可以保留，否则就被操作系统回收了
